apiVersion: v1
kind: Template
metadata:
  name: jmeter-slave-template
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    replicas: "${{REPLICAS}}"
    selector:
      deploymentconfig: ${APPLICATION_NAME}
    template:
      metadata:
        labels:
          app: ${APPLICATION_NAME}
          deploymentconfig: ${APPLICATION_NAME}
      spec:
        containers:
        - name: ${APPLICATION_NAME}
          image: ${IMAGE_NAME}:latest
          imagePullPolicy: Always
          command:
            - /opt/apache-jmeter-3.3/bin/jmeter-server
            - '-Dserver.rmi.localport=50000'
            - '-Dserver_port=1099'
          readinessProbe:
            tcpSocket:
              port: 1099
            initialDelaySeconds: 5
          ports:
          - containerPort: 1099
            protocol: TCP
            name: 1099-tcp
          - containerPort: 50000
            protocol: TCP
            name: 50000-tcp
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 500Mi
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}
        from:
          kind: ImageStreamTag
          name: ${IMAGE_NAME}:latest
      type: ImageChange
parameters:
- name: APPLICATION_NAME
  description: The name for the application.
  displayName: Application name
  value: jmeter-slave
  required: true
- name: IMAGE_NAME
  description: The name for the jmeter image.
  displayName: Jmeter Image name
  value: java-jmeter
  required: true
- name: REPLICAS
  description: Number of slave instances.
  displayName: Number of slave instances.
  value: "3"
  required: true
