apiVersion: v1
kind: Template
labels:
  template: jmeter-build
metadata:
  name: jmeter-build
objects:
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: ${OUTPUT_IMAGE}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${OUTPUT_IMAGE}:latest
    source:
      dockerfile: |-
          FROM registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
          USER root
          RUN curl -o /opt/apache-jmeter-3.3.tgz https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-3.3.tgz && \
            tar -xzf /opt/apache-jmeter-3.3.tgz -C /opt && \
            rm -rf /opt/apache-jmeter-3.3.tgz
          ENV JMETER_HOME="/opt/apache-jmeter-3.3"
          USER 1001"
      type: Dockerfile
    strategy:
      dockerStrategy:
        from:
          kind: DockerImage
          name: ${BASE_IMAGE}
      type: Docker
    triggers: []
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${OUTPUT_IMAGE}
parameters:
- description: The image to layer jmeter onto.
  name: BASE_IMAGE
  required: true
  value: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
- description: Output image.
  name: OUTPUT_IMAGE
  required: true
  value: java-jmeter
